apiVersion: apps/v1
kind: Deployment
metadata:
  name:  microservice1
  namespace: test
  labels:
    app:  microservice1
spec:
  selector:
    matchLabels:
      app: microservice1
  replicas: 1
  template:
    metadata:
      labels:
        app:  microservice1
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  microservice1
        image:  a7medit/k8s
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: microservice1
              key: DB_HOST
        ports:
        - containerPort:  80
          name:  microservice1
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred