name: Docker Image CI

on:
  push:
    branches: [ Master ]
  pull_request:
    branches: [ Master ]

jobs:

  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./microservice1/

    steps:
    - uses: actions/checkout@v3
      with:
        context: .
    - name: Build the Docker image
      run: docker build Microservice1/. --file Dockerfile --tag my-image-name:$(date +%s)
